version: "2025-09-18-01"          # ändert sich bei jeder Veröffentlichung
catalogs:
  # - id: "tiere-de-v1"
  #   version: "1.0.0"
  #   url: "https://raw.githubusercontent.com/svengraziani/flippi-catalog/refs/heads/main/tiere-de-v1.yaml"
  #   meta:
  #     title: "Tiere A1"
  #     locale: "de-AT"
  - id: "verkehrszeichen-de-v1"
    version: "1.0.0"
    url: "https://raw.githubusercontent.com/svengraziani/flippi-catalog/refs/heads/main/verkehrszeichen-de-v1.yaml"
    meta:
      title: "Verkehrszeichen A1"
      locale: "de-AT"